In [31]:
# Boilerplate
import tensorflow as tf
from importlib import reload

import backbone
import classifier
import data_utils
import faster_rcnn
import rpn
import roi_pooling
import geometry

In [61]:
reload(data_utils)
d = data_utils.DataLoaderFull()
print(d.decode_label(tf.constant(0)))
print(d.decode_label(tf.constant(60)))
print(d.decode_label(tf.constant(50)))

Python interpreter in DataLoader.decode_label()
<tf.RaggedTensor []>
<tf.RaggedTensor [[535.0, 444.0, 127.0, 113.0]]>
<tf.RaggedTensor [[539.0, 205.0, 105.0, 98.0], [630.0, 351.0, 95.0, 56.0]]>


In [72]:
reload(rpn)
reload(geometry)
spine=backbone.instantiate('resnet50', {})
rpnwrap=rpn.RPNWrapper(spine)
print(rpnwrap.anchor_xx.shape)
print(rpnwrap.anchor_yy.shape)
print(rpnwrap.hh.shape)
print(rpnwrap.ww.shape)
print(rpnwrap.valid_mask.shape)

(23, 40)
(23, 40)
(4,)
(4,)
(23, 40, 4)


In [73]:
xx = tf.constant(10.)
yy = tf.constant(12.)
ww = tf.constant(4.)
hh = tf.constant(2.)

print(rpnwrap.ground_truth_IoU(d.decode_label(tf.constant(0)), xx, yy, ww, hh))
print(rpnwrap.ground_truth_IoU(d.decode_label(tf.constant(60)), xx, yy, ww, hh))
print(rpnwrap.ground_truth_IoU(d.decode_label(tf.constant(50)), xx, yy, ww, hh))
print(rpnwrap.ground_truth_IoU(d.decode_label(tf.constant(51)), xx, yy, ww, hh))

Python interpreter in rpnwrapper.ground_truth_IoU
Python interpreter in backbone.feature_coords_to_image_coords()
tf.Tensor([], shape=(0,), dtype=float32)
Python interpreter in rpnwrapper.ground_truth_IoU
Python interpreter in geometry.calculate_Iou()
tf.Tensor([0.], shape=(1,), dtype=float32)
Python interpreter in rpnwrapper.ground_truth_IoU
tf.Tensor([0. 0.], shape=(2,), dtype=float32)
tf.Tensor([0. 0.], shape=(2,), dtype=float32)
