In [1]:
# Boilerplate
import tensorflow as tf
from importlib import reload

import backbone
import classifier
import data_utils
import faster_rcnn
import rpn
import roi_pooling
import geometry

In [61]:
# Test the data loading class
reload(data_utils)
d = data_utils.DataLoaderFull()
print(d.decode_label(tf.constant(10))[:4,:])
print(d.decode_label(tf.constant(60))[:4,:])
print(d.decode_label(tf.constant(50))[:4,:])

Python interpreter in DataLoader.decode_label()
tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(4, 4), dtype=float32)
Python interpreter in DataLoader.decode_label()
tf.Tensor(
[[535. 444. 127. 113.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]], shape=(4, 4), dtype=float32)
Python interpreter in DataLoader.decode_label()
tf.Tensor(
[[539. 205. 105.  98.]
 [630. 351.  95.  56.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]], shape=(4, 4), dtype=float32)


In [8]:
# Test the backbone
reload(backbone)
spine = backbone.instantiate('resnet50', {})
features = spine(tf.random.normal((4, 720, 1280, 3)))
print(features.shape)

(4, 23, 40, 2048)


In [100]:
# Test the RPN
reload(rpn)
reload(geometry)
rpnwrap=rpn.RPNWrapper(spine, d.decode_label)
rpnwrap.train_rpn(d.get_training())

Python interpreter in RPNModel._build_anchor_boxes()
Epoch 1/5
Python interpreter in RPNModel.train_step()
Python interpreter in DataLoader.decode_label()
Python interpreter in RPNModel._accumulate_roi()
Python interpreter in rpnwrapper.ground_truth_IoU
Python interpreter in geometry.calculate_Iou()


TypeError: in user code:

    File "/Users/Neil/Library/Python/3.8/lib/python/site-packages/keras/engine/training.py", line 878, in train_function  *
        return step_function(self, iterator)
    File "/Users/Neil/Documents/tensorflow-experiment/great-barrier-reef/rpn.py", line 350, in _accumulate_roi  *
        rois.append(

    TypeError: Failed to convert elements of <dtype: 'float32'> to Tensor. Consider casting elements to a supported type. See https://www.tensorflow.org/api_docs/python/tf/dtypes for supported TF dtypes.
