In [9]:
# This class exists to exercise the functionality of the data importing classes

import tensorflow as tf
import data_utils
from importlib import reload

In [50]:
# Exercise loading the dataset as is
reload(data_utils)
data=data_utils.DataLoader(input_file='tensorflow-great-barrier-reef')
images= data.get_training(validation_split=0.2, batch_size=9, shuffle=True)

# Check that the image batch looks like what we expect
for image,label in images:
    print(image[0])
    print(label[0])   
    break
    # TODO make some plots!

Found 23501 files belonging to 3 classes.
Using 18801 files for training.
Found 23501 files belonging to 3 classes.
Using 4700 files for validation.
tf.Tensor(
[[[  0.       69.       98.     ]
  [  0.       69.       98.     ]
  [  0.       75.      100.71875]
  ...
  [ 26.4375  127.09375 133.8125 ]
  [ 52.5625  136.4375  144.375  ]
  [ 74.84375 169.28125 137.65625]]

 [[  0.28125  70.71875  99.     ]
  [  0.       70.4375   98.71875]
  [  2.       75.71875 105.5625 ]
  ...
  [ 66.875   179.625   147.     ]
  [ 53.28125 145.25    133.53125]
  [ 58.28125 147.375   118.6875 ]]

 [[  0.       75.53125 101.53125]
  [  0.       76.      102.     ]
  [  1.       79.0625   97.46875]
  ...
  [ 54.28125 117.8125  112.125  ]
  [ 46.5625  119.03125 113.625  ]
  [ 44.      116.      103.0625 ]]

 ...

 [[ 64.15625 148.5     128.3125 ]
  [ 91.3125  212.65625 152.28125]
  [105.875   175.8125  119.9375 ]
  ...
  [119.4375  161.96875 142.5    ]
  [145.28125 158.9375  144.53125]
  [174.125   175.53125

In [55]:
# Get a new set of images, these should be different but have correct annotations
reload(data_utils)
data=data_utils.DataLoaderThumbnail(input_file='tensorflow-great-barrier-reef')
images = data.get_training(validation_split=0.2, batch_size=9, shuffle=True)

for image,label in images:
    print(image[0])
    print(label[0])
    break
    # TODO make some plots!

Found 23501 files belonging to 3 classes.
Using 18801 files for training.
Found 23501 files belonging to 3 classes.
Using 4700 files for validation.
tf.Tensor(
[[[  0.       69.       98.     ]
  [  0.       69.       98.     ]
  [  0.       75.      100.71875]
  ...
  [ 26.4375  127.09375 133.8125 ]
  [ 52.5625  136.4375  144.375  ]
  [ 74.84375 169.28125 137.65625]]

 [[  0.28125  70.71875  99.     ]
  [  0.       70.4375   98.71875]
  [  2.       75.71875 105.5625 ]
  ...
  [ 66.875   179.625   147.     ]
  [ 53.28125 145.25    133.53125]
  [ 58.28125 147.375   118.6875 ]]

 [[  0.       75.53125 101.53125]
  [  0.       76.      102.     ]
  [  1.       79.0625   97.46875]
  ...
  [ 54.28125 117.8125  112.125  ]
  [ 46.5625  119.03125 113.625  ]
  [ 44.      116.      103.0625 ]]

 ...

 [[ 64.15625 148.5     128.3125 ]
  [ 91.3125  212.65625 152.28125]
  [105.875   175.8125  119.9375 ]
  ...
  [119.4375  161.96875 142.5    ]
  [145.28125 158.9375  144.53125]
  [174.125   175.53125